### PR TITLE
Update SharedClassesCacheChecker to only delete test-specific cache

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Fixes https://github.com/eclipse/openj9-systemtest/issues/73
Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Tested : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/858/console

**Comment by Mesbah-Alam** [comment]
5x Grinder on Linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/859/console

**Comment by Mesbah-Alam** [comment]
This PR fixes Fixes https://github.com/eclipse/openj9-systemtest/issues/73 and also employs `destroyAll` to destroy all test specific caches created in given non-default cacheDir (instead of individually destroying test caches from non-default location by cacheName).

**Comment by Mesbah-Alam** [comment]
Reviewer : @pshipton

**Comment by pshipton** [comment]
Test build https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-Build/21/

**Comment by pshipton** [comment]
Now it's failing for a different reason, an assertion in the code. Is it possible to see the commands being run?

https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-win_x86-64_cmprssptrs/140/tapTestReport
```
STF 17:43:37.304 - +------ Step 31 - DefinedLocationGroupAccessJava: Monitor workload processes
STF 17:43:37.304 - | Wait for processes to meet expectations
STF 17:43:37.304 - |   Processes: [WL1, WL2, WL3, WL4]
STF 17:43:37.304 - |
STF 17:43:37.304 - Monitoring processes: WL1 WL2 WL3 WL4
STF 17:43:37.436 - Found dump at: C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\core.20190117.174337.2916.0001.dmp
STF 17:43:37.476 - Found dump at: C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\core.20190117.174337.7228.0001.dmp
STF 17:43:39.106 - Found dump at: C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\javacore.20190117.174337.7228.0002.txt
STF 17:43:42.090 - Found dump at: C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\Snap.20190117.174337.7228.0003.trc
STF 17:43:44.403 - Found dump at: C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\Snap.20190117.174337.2916.0003.trc
STF 17:43:44.462 - Found dump at: C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\javacore.20190117.174337.2916.0002.txt
STF 17:43:44.718 - **FAILED** Process WL3 ended with exit code (4294967295) and not the expected exit code/s (0)
STF 17:43:44.719 - Monitoring Report Summary:
STF 17:43:44.719 -   o Process WL1 has crashed unexpectedly
STF 17:43:44.720 -   o Process WL2 ended with the expected exit code (0)
STF 17:43:44.720 -   o Process WL3 has crashed unexpectedly
STF 17:43:44.720 -   o Process WL4 has crashed unexpectedly
```

Found this in 30.WL4.stderr
```
JVMSHRC777W The softmx limit for shared cache usage is smaller than the minimum feasible value 3980759048 bytes.
23:43:37.434 0xee9a00   j9shr.1012   *   ** ASSERTION FAILED ** at CompositeCache.cpp:6276: (((0 != _theca) && hasWriteMutex(currentThread) && (getTotalSize() >= softMaxBytes) && (softMaxBytes >= getUsedBytes())))
```

Found this in the javacore
```
1XECTHTYPE     Current thread history (J9VMThread:0x00000000017D9A00)
3XEHSTTYPE     23:43:37:474859273 GMT j9shr.1012 - * ** ASSERTION FAILED ** at CompositeCache.cpp:6276: (((0 != _theca) && hasWriteMutex(currentThread) && (getTotalSize() >= softMaxBytes) && (softMaxBytes >= getUsedBytes()))) 
3XEHSTTYPE     23:43:37:474851307 GMT j9prt.58 -  <j9shmem_stat exit - contents of controlFile C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\caches\javasharedresources\\C290M4F1A64_DefinedLocationGroupAccessJavaWL3_G35 is corrupted 
3XEHSTTYPE     23:43:37:474838657 GMT j9prt.56 -  >j9shmem_stat entered, name = C290M4F1A64_DefinedLocationGroupAccessJavaWL3_G35 
3XEHSTTYPE     23:43:37:474830133 GMT j9shr.2197 - * CC setCacheAreaBoundaries: The softmx bytes 0 is smaller than the already used bytes 3980759048 
3XEHSTTYPE     23:43:37:474393980 GMT j9prt.58 -  <j9shmem_stat exit - contents of controlFile C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\caches\javasharedresources\\C290M4F1A64_DefinedLocationGroupAccessJavaWL3_G35 is corrupted 
3XEHSTTYPE     23:43:37:474383497 GMT j9prt.56 -  >j9shmem_stat entered, name = C290M4F1A64_DefinedLocationGroupAccessJavaWL3_G35 
3XEHSTTYPE     23:43:37:474374591 GMT j9shr.1028 -   CC setCacheAreaBoundaries: finalSegmentStart=000000000FA99000, newCacheEnd=0000000022640000, _theca->totalBytes=314572608 
3XEHSTTYPE     23:43:37:474367741 GMT j9shr.1027 -   CC setCacheAreaBoundaries: finalSegmentStart=000000000FA981E0, origCacheEnd=0000000022640000, _theca->totalBytes=314572608 
3XEHSTTYPE     23:43:37:474357480 GMT j9shr.1026 -  >CC setCacheAreaBoundaries: Entering 
3XEHSTTYPE     23:43:37:474347666 GMT j9shr.2269 -   CC startup: initializing a new cache 
```

**Comment by Mesbah-Alam** [comment]
Interesting why the crash did not occur in the 5x Grinder on Linux and also in the 1x Grinder on Windows during testing. 

 ```JVMSHRC777W The softmx limit for shared cache usage is smaller than the minimum feasible value 3980759048 bytes.```

- Is the 'minimum feasible value for softmx universal or platform specific? 

The Workload that crashes, WL3 runs the following command: 

```
C:/Users/jenkins/workspace/Test-extended.system-JDK8-win_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -Xshareclasses:name=DefinedLocationGroupAccessJavaWL3,cacheDir=C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\caches,nonpersistent,groupAccess -Xcompressedrefs -classpath C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\jvmtest\systemtest\stf\stf.load\bin;C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\jvmtest\systemtest\stf\stf.core\bin;C:/Users/jenkins/workspace/Test-extended.system-JDK8-win_x86-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar;C:/Users/jenkins/workspace/Test-extended.system-JDK8-win_x86-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar;C:/Users/jenkins/workspace/Test-extended.system-JDK8-win_x86-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs/junit-4.12/junit-4.12.jar;C:/Users/jenkins/workspace/Test-extended.system-JDK8-win_x86-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar;C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\jvmtest\systemtest\openjdk-systemtest\openjdk.test.lang\bin;C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\jvmtest\systemtest\openjdk-systemtest\openjdk.test.util\bin;C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\jvmtest\systemtest\openjdk-systemtest\openjdk.test.math\bin net.adoptopenjdk.loadTest.LoadTest -resultsDir C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results -resultsPrefix 29.WL3. -dumpRequested false -reportFailureLimit 1 -abortAtFailureLimit 10 -maxTotalLogFileSpace 200M -maxSingleLogSize 1/25 -suite.mini-mix.inventoryFile C:/Users/jenkins/workspace/Test-extended.system-JDK8-win_x86-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15477678633841/SharedClassesAPI_0/20190117-174310-SharedClassesAPI/results/29.WL3.inventory/openjdk.test.load/config/inventories/mix/mini-mix.xml -suite.mini-mix.inventoryExcludeFile C:/Users/jenkins/workspace/Test-extended.system-JDK8-win_x86-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15477678633841/SharedClassesAPI_0/20190117-174310-SharedClassesAPI/results/29.WL3.inventory/openjdk.test.load/config/inventories/mix/mini-mix_exclude.xml -suite.mini-mix.threadCount 3 -suite.mini-mix.totalNumberTests 78 -suite.mini-mix.selection random -suite.mini-mix.seed -1 -suite.mini-mix.repeatCount 1 -suite.mini-mix.thinkingTime 0ms..0ms
```

**Pull request merged**
