### PR TITLE
Limit all variants of SharedClasses test to 10 minutes

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Related to : https://github.com/eclipse/openj9-systemtest/issues/103

Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Testing multi-thread multi-cl test: Test_grinder/job/Grinder/2821/console

**Comment by pshipton** [comment]
```
10:19:58  The following files were modified and have incorrect copyrights
[Pipeline] echo
10:19:58  openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/test/sc/LoaderSlaveMultiJar.java
[Pipeline] echo
10:19:58  openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/test/sc/LoaderSlaveMultiThread.java
[Pipeline] echo
10:19:58  openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/test/sc/LoaderSlaveMultiThreadMultiCL.java
```

**Comment by Mesbah-Alam** [comment]
@pshipton : The test passed. I've also updated those 3 classes to have the right copyright header. Please merge this PR.

**Comment by pshipton** [comment]
@Mesbah-Alam the original copyright date was 2017, but was changed to 2016. Please confirm these files should be copyright from 2016.

**Comment by Mesbah-Alam** [comment]
@pshipton : Since these classes pertain to the SharedClasses.java test (https://github.com/Mesbah-Alam/openj9-systemtest/blob/master/openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java) - They may contain the same copyright header as SHaredClasses.java. I just copied it from there (which starts with "Copyright (c) 2016, 2019 IBM Corp. and others").

**Comment by pshipton** [comment]
@Mesbah-Alam were these classes written in 2016 or 2017? I can't tell from your answer. The copyright start year should match when the code was written.

**Comment by Mesbah-Alam** [comment]
@pshipton : I am not sure exactly in which year the classes under `net.openj9.test.sc` were written (they were ported to STF from the old javatest repo); but they were definitely written before 2016.

**Pull request merged**
