### PR TITLE
Fix regex for checking SSC output - include all possible Java versions

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves https://github.com/eclipse/openj9/issues/2315
Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Tested with Java 8 : https://hyc-runtimes-jenkins.swg-devops.com/view/Test_system/job/Grinder/17/consoleFull

Tested with Java 10: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_system/job/Grinder/19/console

**Comment by Mesbah-Alam** [comment]
@llxia - Could you please review and merge this PR?

**Comment by llxia** [comment]
Do we have issue open for step 6 failure?

**Comment by Mesbah-Alam** [comment]
Created new issue to handle the failure in step 6 : https://github.com/eclipse/openj9-systemtest/issues/33

**Pull request merged**
