### PR TITLE
Enable systemtest on z/OS

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/139 
Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
@lumpfish - please review.

**Comment by DanHeidinga** [comment]
We want to hold off on this as the .gitattributes file will break anyone using a newer version of GIT.  The  `worktree-encoding` attribute is now recognized by git 2.18, which the current file unfortunately tells git to treat everything as ebcdic.

**Comment by Mesbah-Alam** [comment]
@DanHeidinga Hi Dan, thanks for pointing this out. 

Is there any alternative solution we can adopt here instread? This change is based on https://github.com/eclipse/openj9/blob/master/.gitattributes - which would also break based on the same principle you stated above.

**Comment by DanHeidinga** [comment]
Unfortunately, we'd already committed a similar change to OpenJ9 & OMR.  Working through the right approach in https://github.com/eclipse/openj9/pull/2254, though Devin's PR is likely a more correct solution.

**Comment by Mesbah-Alam** [comment]
@DanHeidinga Hi Dan, I was looking at the conversation and the PR delivered in https://github.com/eclipse/openj9/pull/2254. The only change the PR contains is removal of the ebcdic parts in the .gitattributes file. It is not clear what new workaround has been adopted instead to convert texts to ebcdic now. Could you please elaborate on it a bit (e.g. is it only adding `git checkout-index -f -a `) ?

**Comment by smlambert** [comment]
Dan is on vacation, perhaps you can ask @pshipton for more details on https://github.com/eclipse/openj9/pull/2310 and related issue.

**Comment by pshipton** [comment]
Due to some reluctance on the part of the OpenJ9/OMR projects to deliver these files, eclipse/openj9#2310 and the omr equivalent was basically delivered to the z/OS repository instead of the public repos. By itself this file doesn't have any affect. The z/OS builds renames/copies it to overwrite the .gitattributes files and re-runs some of the git processing.

**Comment by Mesbah-Alam** [comment]
As part of enabling systemtest on z/OS, we had introduced the `.gitattributes` file in the 3 system test repositories (via this PR, https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/140 and https://github.com/AdoptOpenJDK/stf/pull/41). 

Quoting from https://github.com/eclipse/openj9/pull/2310 :  

```
On a zos platform the openjdk extensions file ./closed/get_j9_source.sh will be modified to copy this .gitattributes.zos file to .git/info/attributes and the files refreshed. This will then emncode/decode the files.
```
It looks like we need to do something similar in the above 3 system test PRs as well, to what was done in https://github.com/eclipse/openj9/pull/2310 . 

> The z/OS build renames/copies them to overwrite the regular .gitattributes files and re-runs some of the git processing

@pshipton - Is the above renames/copies and additional git processing done in `./closed/get_j9_source.sh ` -- could you please point us to that file?

**Comment by pshipton** [comment]
It is done in the z/OS specific repo. Please check with Steve Groerger for the details.

**Comment by Mesbah-Alam** [comment]
I have updated the three 3 PRs above based on eclipse/openj9#2310.

- Added .gitattributes.zos (left the existing .gitattributes file as is)
- Added processing logic in [systemtest/build.xml script](https://github.com/Mesbah-Alam/openjdk-tests/blob/enableTestingOnZos/systemtest/build.xml) to copy this .gitattributes.zos file to .git/info/attributes and refresh files, as described by Steve in eclipse/openj9#2310
```
cp .gitattributes.zos .git/info/attributes
git rm --cached -r -q .
git reset --hard
```
Test is passing on z/OS with the above changes as evident in: https://hyc-runtimes-jenkins.swg-devops.com/view/all/job/WIP_Grinder/30/console

**Comment by smlambert** [comment]
Yes, I will wait, so they are co-ordinated submissions.

**Pull request merged**
