### PR TITLE
Use curl to download systemtest prereqs when on zos

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Fixes https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/127
Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Tested on zOS with: https://urv-jenkins.canlab.ibm.com:9095/view/SV_Tests/job/ibmjava8_systemtest_s390x_zos/69/console

Tested on non-Zos with: https://urv-jenkins.canlab.ibm.com:9095/view/SV_Tests/job/ibmjava8_systemtest_x86-64_linux/442/console

**Comment by Mesbah-Alam** [comment]
Sophia Guo: please review.

**Comment by Mesbah-Alam** [comment]
This PR adds equivalent changes to openj9.build/include/top.xml as added in stf.build/include/top.xml via https://github.com/AdoptOpenJDK/stf/pull/39

**Comment by sophia-guo** [comment]
Curious why we have exactly files in two different repos? That basically means we need to maintain two copies. Same for review have to review same changes for three repos and got confused if i've done the reviews.

https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/131
https://github.com/AdoptOpenJDK/stf/pull/39

**Comment by Mesbah-Alam** [comment]
@sophia-guo : You are right. The files are not exactly the same, but very similar. It is difficult to maintain and also review PRs for (as you mentioned above). I'd have an issue opened to find out the original reason why three different top.xml files were created at the first place and collapse them to only one (ideally).

**Pull request merged**
