### PR TITLE
Check jvm version using java.vm.version property

### PR DESCRIPTION
**Pull request by lumpfish**
Signed-off-by: Simon Rushton <rushton@uk.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
@smlambert - could you please merge this change?

**Comment by Mesbah-Alam** [comment]
This change causes `stf`, `openjdk-systemtest` and` openj9-systemtest` to **not** compile in the Jenkins build: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/312/consoleFull

The same test works when run from master: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/310/parameters/

**Comment by smlambert** [comment]
So I am presuming we are still investigating the failures caused by this change?

**Comment by Mesbah-Alam** [comment]
@smlambert - yes. Please hold off on this one for the time being.

**Comment by lumpfish** [comment]
The change caused the build for this repository to fail by introducing a dependency on a property supplied only by the testkitgen tool, preventing a user from building the repository successfully following the instructions in this repository.  This PR removes the need for that property to be supplied by testkitgen. I have tested that the build now works.  
@mesbah is running some tests to make sure that a build initiated by testkitgen still works as it did before.

**Comment by AdamBrousseau** [comment]
Jenkins copyright check

**Comment by Mesbah-Alam** [comment]
Hi @lumpfish, in the [Grinder build](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/312/consoleFull,) (which simulates the real pipeline Jenkins build),  the `java8_vm_version` is set to `hotspot` even though the build was launched with an OpenJ9 SDK. This PR is setting `java8_vm_version` property. I wonder why it is being set to the wrong value, and if this is contributing to the fact that the build is ending up not compiling any system test artifacts. 

You added a change to set

**Comment by Mesbah-Alam** [comment]
@lumpfish - There is an echo inside the PR, in the newly added `<macrodef name="get-vm-version"` : `<echo message="vm is @{vm}"/>`. This, in the [Grinder build](url
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/312/consoleFull), prints out the following: 

` [echo] vm is master-7259d3ac` 

This explains why the macrodef `get-vm-version` is ending up setting java8_vm_version to 'hotspot'.

**Comment by lumpfish** [comment]
java.vm.name looks better:
IBM SDK 8 says "IBM J9 VM"
AdoptOpenJDK openj9 builds say "Eclipse OpenJ9 VM"
AdoptOpenJDK hotspot 8 build says: "OpenJDK 64-Bit Server VM"

So it looks like just check java.vm.name for "J9" will be satisfactory.

**Comment by lumpfish** [comment]
@Mesbah-Alam - I've made the change to use java.vm.name and tested on my local machine.  Please could you try again on the Jenkins pipeline?

**Comment by Mesbah-Alam** [comment]
@lumpfish thanks for making the changes. It's working now: 
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/558/console

**Comment by Mesbah-Alam** [comment]
@smlambert - please merge this PR when possible.

**Comment by Mesbah-Alam** [comment]
@lumpfish - the copyright check has failed by the way. Please update '2017' to '2017, 2018' in the copyright notice.

**Comment by lumpfish** [comment]
Updated the copyright as requested.

**Pull request merged**
